version: '3'

services:
  db:
    image: mysql:5
    restart: always
    environment:
      MYSQL_DATABASE: inter_backend_production
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"
    volumes:
      - ./data/db:/var/lib/mysql
    command: bash -c "chmod -R 755 /var/lib/mysql && docker-entrypoint.sh mysqld"

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && rails s -p 3000 -b '0.0.0.0'"
    environment:
      RAILS_ENV: development
      DATABASE_URL: mysql2://root:123456@db/inter_backend_production
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
