openapi: 3.0.1
info:
  title: API V1
  description: inter_backend
  version: v1
paths:
  "/api/v1/auth":
    post:
      tags:
        - auth
      summary: Get information of user
      description: That route is used to get information about an user
      parameters:
        - name: Authorization
          in: header
          description: Token containing email and password of the user
          required: true
          example: "token"
        - name: Content-Type
          in: header
          description: Type of the content sent in the request
          required: true
          example: "application/json"
        - name: Accept
          in: header
          description: Type of the content accepted in the response
          required: true
          example: "application/json"
        - name: AppKey
          in: header
          description: Numeric key to identify the application
          required: true
          example: "12345"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    example: "token"
                  status:
                    type: string
                    example: "SUCCESS"
                  message:
                    type: string
                    example: "User logged in"
        "401":
          description: Unauthorized
        "400":
          description: Bad Request
