
default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: 123456
  port: 3306
  host: localhost

development:
  <<: *default
  database: inter_backend_development

test:
  <<: *default
  database: inter_backend_test

production:
  <<: *default
  database: inter_backend_production
  username: inter_backend
  password: <%= ENV["INTER_BACKEND_DATABASE_PASSWORD"] %>
