default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: 123456
  host: localhost
  port: 3306

development:
  <<: *default
  database: inter_backend_development

test:
  <<: *default
  database: inter_backend_test

production:
  <<: *default
  url: mysql://root:Ep8xD9rqYEs8Hhm2eM81@containers-us-west-138.railway.app:6506/railway
