default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: Ep8xD9rqYEs8Hhm2eM81
  host: containers-us-west-138.railway.app
  port: 6506

development:
  <<: *default
  database: inter_backend_development

test:
  <<: *default
  database: inter_backend_test

production:
  <<: *default
  database: railway
  username: root
  password: Ep8xD9rqYEs8Hhm2eM81
  host: containers-us-west-138.railway.app
  port: 6506
